app:
  replicas: 4
  env: dev
  image: vikashashoke/ui
  computers: | 
    limits:
     cpu: 2
     memory: 4Gi
    requests:
     cpu: 2
     memory: 4Gi
    
hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 4
  targetCPUUtilizationPercentage: 50